# modules/reporter.py
from fpdf import FPDF
from datetime import datetime
import os
from config import APP_NAME, APP_VERSION, APP_AUTHOR, REPORTS_DIR

RISK_COLORS = {
    "CRITICAL": (220, 50,  50),
    "HIGH":     (230, 100, 30),
    "MEDIUM":   (200, 150, 0),
    "LOW":      (50,  150, 50),
    "NONE":     (50,  180, 50),
}

def clean_text(text):
    if not text:
        return ""
    return (text
        .replace("\u2014", "-")
        .replace("\u2013", "-")
        .replace("\u2018", "'")
        .replace("\u2019", "'")
        .replace("\u201c", '"')
        .replace("\u201d", '"')
        .replace("\u2026", "...")
    )

def clean_banner(banner):
    if not banner:
        return "No banner captured"
    lines = banner.replace("\r\n", "\n").split("\n")
    first = next((l.strip() for l in lines if l.strip()), "No banner captured")
    return clean_text(first)[:80]

def wrap_text(text, chars_per_line):
    """
    Manually wraps text to fit within a character limit per line.
    Returns a list of lines.
    """
    words = text.split()
    lines = []
    current = ""
    for word in words:
        test = (current + " " + word).strip()
        if len(test) <= chars_per_line:
            current = test
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines if lines else [""]


class VulnScanReport(FPDF):

    def header(self):
        self.set_fill_color(30, 30, 40)
        self.rect(0, 0, 210, 20, "F")
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 5)
        self.cell(0, 10, f"{APP_NAME} v{APP_VERSION}", ln=False)
        self.set_font("Helvetica", "", 10)
        self.set_xy(-70, 5)
        self.cell(60, 10, f"by {APP_AUTHOR}", align="R")
        self.set_text_color(0, 0, 0)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10,
                  f"Page {self.page_no()} - Generated by {APP_NAME}",
                  align="C")


def generate_report(target, mode, scan_results, assessment):
    pdf = VulnScanReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    L = 10    # left margin
    W = 190   # usable width

    # ── TITLE ────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 30, 40)
    pdf.cell(0, 12, "Vulnerability Scan Report", ln=True, align="C")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    scan_date = datetime.now().strftime("%B %d, %Y at %H:%M:%S")
    pdf.cell(0, 6,
             f"Target: {target}   |   Mode: {mode} Scan   |   Date: {scan_date}",
             ln=True, align="C")
    pdf.ln(8)

    # ── RISK BADGE ───────────────────────────────────────────────
    risk       = assessment["overall_risk"]
    risk_color = RISK_COLORS.get(risk, (100, 100, 100))
    pdf.set_fill_color(*risk_color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 15)
    pdf.cell(0, 13, f"Overall Risk: {risk}", ln=True, align="C", fill=True)
    pdf.ln(6)

    # ── STATS ROW ────────────────────────────────────────────────
    stats = [
        ("Open Ports",   str(len(scan_results))),
        ("Total CVEs",   str(assessment["total_cves"])),
        ("Highest CVSS", str(assessment["highest_score"])),
        ("Critical",     str(assessment["critical_count"])),
        ("High",         str(assessment["high_count"])),
        ("Medium",       str(assessment["medium_count"])),
    ]
    col = W / len(stats)

    for label, value in stats:
        pdf.set_fill_color(240, 240, 250)
        pdf.set_font("Helvetica", "B", 15)
        pdf.set_text_color(30, 30, 40)
        pdf.cell(col, 11, value, border="LTR", align="C", fill=True)
    pdf.ln()

    for label, value in stats:
        pdf.set_fill_color(240, 240, 250)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(col, 7, label, border="LBR", align="C", fill=True)
    pdf.ln(12)

    # ── EXECUTIVE SUMMARY ────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(30, 30, 40)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 8, "  Executive Summary", ln=True, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.ln(3)
    pdf.multi_cell(0, 6, clean_text(assessment["summary"]))
    pdf.ln(6)

    # ── DETAILED FINDINGS ────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(30, 30, 40)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 8, "  Detailed Findings", ln=True, fill=True)
    pdf.ln(4)

    # Column widths — must sum to W (190)
    W_ID   = 44
    W_CVSS = 16
    W_SEV  = 22
    W_DESC = W - W_ID - W_CVSS - W_SEV   # = 108

    LINE_H = 5   # row line height in mm
    CHARS  = 58  # approx chars per line at font size 8 for W_DESC=108

    for item in scan_results:
        port    = item["port"]
        service = item["service"]
        banner  = clean_banner(item["banner"])
        cves    = item.get("cves", [])

        # Port header bar
        pdf.set_fill_color(60, 60, 80)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, f"  Port {port} - {service}", ln=True, fill=True)

        # Banner row
        pdf.set_fill_color(248, 248, 255)
        pdf.set_text_color(80, 80, 80)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(26, 6, "Banner:", fill=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 6, banner, ln=True)

        if cves:
            pdf.ln(2)

            def draw_table_header():
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_fill_color(220, 220, 230)
                pdf.set_text_color(30, 30, 40)
                pdf.cell(W_ID,   6, "CVE ID",      border=1, fill=True)
                pdf.cell(W_CVSS, 6, "CVSS",        border=1, fill=True, align="C")
                pdf.cell(W_SEV,  6, "Severity",    border=1, fill=True, align="C")
                pdf.cell(W_DESC, 6, "Description", border=1, fill=True)
                pdf.ln()

            draw_table_header()

            for cve in cves:
                severity = cve["severity"]
                color    = RISK_COLORS.get(severity, (100, 100, 100))

                # Pre-wrap the description to fit W_DESC column
                desc  = clean_text(cve["description"]).replace("\n", " ").strip()
                lines = wrap_text(desc, CHARS)
                row_h = len(lines) * LINE_H

                # Check if row fits — add new page and redraw header if not
                y = pdf.get_y()
                if y + row_h > 267:
                    pdf.add_page()
                    draw_table_header()
                    y = pdf.get_y()

                # CVE ID cell
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(0, 0, 0)
                pdf.set_fill_color(255, 255, 255)
                pdf.set_xy(L, y)
                pdf.cell(W_ID, row_h, cve["id"], border=1)

                # CVSS cell
                pdf.set_xy(L + W_ID, y)
                pdf.cell(W_CVSS, row_h, str(cve["cvss_score"]),
                         border=1, align="C")

                # Severity cell — colored background
                pdf.set_fill_color(*color)
                pdf.set_text_color(255, 255, 255)
                pdf.set_xy(L + W_ID + W_CVSS, y)
                pdf.cell(W_SEV, row_h, severity, border=1, align="C", fill=True)

                # Description — multi-line, wraps correctly
                pdf.set_text_color(0, 0, 0)
                pdf.set_fill_color(255, 255, 255)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_xy(L + W_ID + W_CVSS + W_SEV, y)
                pdf.multi_cell(W_DESC, LINE_H, "\n".join(lines), border=1)

        else:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(130, 130, 130)
            pdf.cell(0, 6, "  No CVEs found for this service.", ln=True)
            pdf.set_text_color(0, 0, 0)

        pdf.ln(5)

    # ── DISCLAIMER ───────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5,
        "DISCLAIMER: This report was generated by VulnScan for authorized "
        "security assessment purposes only. Only scan systems you own or have "
        "explicit written permission to test. Unauthorized scanning may violate "
        "computer fraud laws in your jurisdiction."
    )

    # ── SAVE ─────────────────────────────────────────────────────
    filename = (
        f"vulnscan_{target.replace('.', '_')}_"
        f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    )
    filepath = os.path.join(REPORTS_DIR, filename)
    pdf.output(filepath)
    print(f"\nReport saved to: {filepath}")
    return filepath